/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface:                    '#fbf9f8',
        background:                 '#fbf9f8',
        primary:                    '#000000',
        secondary:                  '#6d5a52',
        tertiary:                   '#000000',
        outline:                    '#747878',
        'outline-variant':          '#c4c7c7',
        'on-surface':               '#1b1c1b',
        'on-surface-variant':       '#444748',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#858383',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#725e56',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#8d827d',
        'on-background':            '#1b1c1b',
        'surface-bright':           '#fbf9f8',
        'surface-dim':              '#dbdad9',
        'surface-variant':          '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f5f3f2',
        'surface-container':        '#efedec',
        'surface-container-high':   '#e9e8e7',
        'surface-container-highest':'#e4e2e1',
        'primary-container':        '#1c1b1b',
        'primary-fixed':            '#e5e2e1',
        'primary-fixed-dim':        '#c8c6c5',
        'secondary-container':      '#f5dad0',
        'secondary-fixed':          '#f7ddd3',
        'secondary-fixed-dim':      '#dac1b7',
        'tertiary-container':       '#211a17',
        'tertiary-fixed':           '#eee0da',
        'tertiary-fixed-dim':       '#d1c4be',
        'inverse-surface':          '#303030',
        'inverse-primary':          '#c8c6c5',
        'inverse-on-surface':       '#f2f0ef',
      },
      fontFamily: {
        headline: ['Italiana', 'serif'],
        body:     ['Jost', 'sans-serif'],
        label:    ['Jost', 'sans-serif'],
        serif:    ['Italiana', 'serif'],
        sans:     ['Jost', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
